- name: Run show commands on Cisco 2821 and 6800
  hosts: cisco_routers
  gather_facts: no
  connection: network_cli
  collections:
    - cisco.ios
  
  vars:
    ansible_network_os: ios
    ansible_become: yes
    ansible_become_method: enable
  
  tasks:
    - name: run "no ip domain lookup"
      ios_config:
        lines:
          - no ip domain lookup
     
    - name: backup tasks
      ios_config:
        backup: yes 