[cisco_routers]
6800 ansible_host=192.168.251.61 ansible_user=$SSH_USER ansible_ssh_pass=$PASS_6800 ansible_network_os=ios ansible_connection=network_cli ansible_become_password=$PASS_6800
2821 ansible_host=192.168.251.90 ansible_user=$SSH_USER ansible_ssh_pass=$PASS_2821 ansible_network_os=ios ansible_connection=network_cli ansible_become_password=$PASS_2821
# 3650 ansible_host=192.168.251.10 ansible_user=gabe ansible_ssh_pass=s144 ansible_network_os=ios ansible_connection=network_cli ansible_become_password=s144 ansible_become=yes ansible_become_method=enable
